version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel_app:v1
    container_name: laravel_app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    command: ["php", "artisan", "serve", "--host", "0.0.0.0", "--port", "8000"]
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network
    # command: php artisan serve --host 0.0.0.0 --port 8000

  db:
    image: mysql:latest
    container_name: myproject_db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: myproject_db
      MYSQL_USER: myproject_user
      MYSQL_PASSWORD: myproject_pass
      MYSQL_ROOT_PASSWORD: myproject_root
      SERVICE_TAGS: dev
      SERVICE_NAME: db
    volumes:
      - dbdata:/var/lib/mysql/
    networks:
      - app-network

  redis:
    image: redis:latest

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: myproject_phpmyadmin
    restart: unless-stopped
    tty: true
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: myproject_root
    ports:
      - "8080:80"
    networks:
      - app-network
      
volumes:
  dbdata:
    driver: local
networks:
  app-network:
    driver: bridge
